### ISSUE TITLE
Handle of 'Cannot send user message' rejection

### ISSUE THREAD

**Issue by HaydenMeloche** [HaydenMeloche/AlphaConsoleBot#63]
this promise rejection happens when the user doesnt allow PMs. 
```js
Unhandled Rejection at: Promise Promise {
  <rejected> { DiscordAPIError: Cannot send messages to this user
    at item.request.gen.end (C:\Users\Hayden\Documents\GitHub\AlphaConsoleBot\node_modules\discord.js\src\rest\handlers\RequestHandler.js:79:65)
    at then (C:\Users\Hayden\Documents\GitHub\AlphaConsoleBot\node_modules\snekfetch\src\index.js:218:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  name: 'DiscordAPIError',
  message: 'Cannot send messages to this user',
  path: '/api/v7/channels/365272896115048469/messages',
  code: 50007 } } reason: { DiscordAPIError: Cannot send messages to this user
    at item.request.gen.end (C:\Users\Hayden\Documents\GitHub\AlphaConsoleBot\node_modules\discord.js\src\rest\handlers\RequestHandler.js:79:65)
    at then (C:\Users\Hayden\Documents\GitHub\AlphaConsoleBot\node_modules\snekfetch\src\index.js:218:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  name: 'DiscordAPIError',
  message: 'Cannot send messages to this user',
  path: '/api/v7/channels/365272896115048469/messages',
  code: 50007 }
```

Solution = Maybe tag them in general and tell them that they can't be DM'd.

**Comment by ThePjpollie** [comment]
I would rather suggest tagging them in #bot-spam by the way. That's a spam channel and won't really interrupt a lot of people.
